-- Add missing columns to admins table
ALTER TABLE admins ADD COLUMN IF NOT EXISTS department VARCHAR(255);
ALTER TABLE admins ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20);
ALTER TABLE admins ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE admins ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
